version: '2'
services:
  nginx:
    image: nginx:1.11.12-alpine
    volumes:
    - ./project:/www
    - ./docker/nginx/conf.d:/etc/nginx/conf.d
    - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
  php:
    build: ./docker/php/build
    volumes:
    - ./project:/www:rw
    - ./docker/php/php-fpm.conf:/usr/local/etc/php-fpm.conf
    - ./docker/php/php.docker.ini:/usr/local/etc/php/php.ini
    working_dir: /www/
  mysql:
    image: mariadb:10.3.1
    volumes:
    - ./docker/mariadb/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_USER: notification
      MYSQL_PASSWORD: dadqeQWER
      MYSQL_DATABASE: notification

